version: '3.7'

services:
  mysql:
    image: wonfs/docker_assignment-mysql
    container_name: mysql
    ports:
      - 3306:3306

  api:
    image: wonfs/docker_assignment-api
    container_name: api
    ports:
      - 5200:5200
    depends_on:
      - mysql
    environment:
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=NewsDB
      - DB_HOST=mysql
      - PORT=5200

  ui:
    image: wonfs/docker_assignment-ui
    container_name: ui
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - API_URL=http://api
